version: '3.4'
services:

  siteapp:
    build:
      context: ./site-app
      target: composer
    container_name: siteapp
    tty: true
    working_dir: /var/www
    volumes:
      - ./site-app:/var/www/site-app

  webserver:
    build:
      context: .
      target: base
    container_name: webserver
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./site-app:/var/www/site-app
