version: '3.4'
services:

  siteapp:
    build:
      context: ./site-app
      target: base
    container_name: siteapp
    tty: true
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    working_dir: /var/www
    volumes:
      - ./site-app:/var/www/site-app
    user: ${DOCKER_USER:-0}

  webserver:
    build:
      context: .
      target: base
    container_name: webserver
    tty: true
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "${DOCKER_HOST:-80}:80"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./site-app:/var/www/site-app
