version: '3'
services:

  siteapp:
    image: ${ECR_PROD_SITE_APP}:${CI_COMMIT_SHA}
    environment:
      APP_NAME: ${APP_NAME}
      APP_ENV: ${APP_ENV}
      APP_KEY: ${APP_KEY}
      APP_DEBUG: ${APP_DEBUG}
      LOG_CHANNEL: stderr
      APP_URL: http://localhost
      APP_TIMEZONE: UTC
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      CACHE_DRIVER: file
      QUEUE_CONNECTION: sync
    logging:
      driver: awslogs
      options:
        awslogs-group: merchant-api
        awslogs-region: ${AWS_REGION}
        awslogs-stream-prefix: ${APP_ENV}

  webserver:
    image: ${ECR_PROD_WEB_SERVER}:${CI_COMMIT_SHA}
    ports:
      - "80:80"
    logging:
      driver: awslogs
      options:
        awslogs-group: merchant-api
        awslogs-region: ${AWS_REGION}
        awslogs-stream-prefix: ${APP_ENV}
